name: Dev Pipeline Deploy To ECS

on:
    workflow_dispatch:

env:
    SERVICE_NAME: ct-backend-service
    CLUSTER_NAME: pythonbackend
    CONTAINER_NAME: ct-backend
    TASK_DEFINITION: pythonbackend

jobs:
    build:
        runs-on: ubuntu-latest
        
        outputs:
            image_version: ${{ steps.image_version.outputs.version }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                ref: master

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.DEV_AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and push
              id: docker_image
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ vars.DEV_IMAGE_REPO }}:latest
            
            - name: Publish Pushed Image Version
              id: image_version
              run: echo "version=latest" >> "$GITHUB_OUTPUT"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.DEV_AWS_REGION }}

            - name: Download task definition
              run: |
                aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION }} --query taskDefinition > task-definition.json
                echo "image version is : ${{needs.build.outputs.image_version}}"
            - name: Update ECS task definition Image Name
              id: task-def
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                task-definition: task-definition.json
                container-name: ${{ env.CONTAINER_NAME }}
                image: "${{ vars.DEV_IMAGE_REPO }}:${{ needs.build.outputs.image_version }}"
      
            - name: Deploy Amazon ECS task definition
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: ${{ env.SERVICE_NAME }}
                cluster: ${{ env.CLUSTER_NAME }}
                wait-for-service-stability: false
            
            
